web:
    image: nginx-dev
    links:
        - php
        - storage
    ports:
        - 80:80
    volumes_from:
        - storage
    environment:
        PHP_FPM: php:9000
        DOCUMENT_ROOT: /var/www/html
        SERVER_NAME: app.dev        
php:
    image: php-dev
    volumes_from:
        - storage
    links:
        - database
        - storage
storage:
    image: storage-dev
    volumes:
        - ../../project/app:/var/www/html
database:
    image: mysql-dev
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
        MYSQL_DATABASE: wordpress
    ports:
        - 3306:3306
